"""Make this folder usable from any coding agent. Idempotent; re-run after editing config/ or .agents/.

  * MCP: config/mcp.servers.json -> .mcp.json (Claude Code), .cursor/mcp.json,
         .vscode/mcp.json, .gemini/settings.json, .codex/config.toml
  * Docs: .agents/skills/resolve-delivery/references/platforms.md is generated from
    resolve_forge.domain.formats, so specs live in one place (the code).
  * Skills/agents: .agents/ is canonical; .claude/{skills,agents} are links to it
    (junctions on Windows, symlinks elsewhere), so there is one copy to maintain.

Usage:  python scripts/sync.py [--check]
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPSTREAM = ROOT / "vendor" / "davinci-resolve-mcp"
LINKS = {ROOT / ".claude" / "skills": ROOT / ".agents" / "skills",
         ROOT / ".claude" / "agents": ROOT / ".agents" / "agents"}


def load_servers() -> dict[str, dict]:
    raw = (ROOT / "config" / "mcp.servers.json").read_text(encoding="utf-8")
    raw = raw.replace("{ROOT}", ROOT.as_posix()).replace("{UPSTREAM}", UPSTREAM.as_posix())
    servers = json.loads(raw)["servers"]
    return {name: {k: v for k, v in spec.items() if k != "description"} for name, spec in servers.items()}


def toml_value(value) -> str:
    if isinstance(value, dict):
        return "{ " + ", ".join(f'"{k}" = {toml_value(v)}' for k, v in value.items()) + " }"
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    return json.dumps(value)


def platforms_doc() -> str:
    sys.path.insert(0, str(ROOT / "mcp" / "resolve-forge" / "src"))
    from resolve_forge.domain import formats  # pure module: no Resolve, no MCP needed

    return ("# Plataformas y specs de entrega\n\n"
            "> Generado por `python scripts/sync.py` desde `resolve_forge/domain/formats.py`. No editar a mano.\n\n"
            + formats.markdown_table()
            + "\nSafe zone = fracción del frame tapada por la interfaz de la app. Caras, subtítulos y CTAs van dentro "
              "del resto (`list_formats` → `safe_rect_px`). True peak −1 dBTP en todas.\n")


def render(servers: dict[str, dict]) -> dict[Path, str]:
    std = json.dumps({"mcpServers": servers}, indent=2) + "\n"
    vscode = json.dumps({"servers": {n: {"type": "stdio", **s} for n, s in servers.items()}}, indent=2) + "\n"
    codex = "# generated by scripts/sync.py — edit config/mcp.servers.json instead\n" + "".join(
        f"\n[mcp_servers.{name}]\n" + "".join(f"{k} = {toml_value(v)}\n" for k, v in spec.items() if v != {})
        for name, spec in servers.items())
    return {ROOT / ".mcp.json": std, ROOT / ".cursor" / "mcp.json": std,
            ROOT / ".gemini" / "settings.json": std, ROOT / ".vscode" / "mcp.json": vscode,
            ROOT / ".codex" / "config.toml": codex,
            ROOT / ".agents" / "skills" / "resolve-delivery" / "references" / "platforms.md": platforms_doc()}


def link(dst: Path, src: Path) -> str:
    if dst.exists() or dst.is_symlink():
        return "ok"
    dst.parent.mkdir(parents=True, exist_ok=True)
    if os.name == "nt":  # junctions need no admin rights
        subprocess.run(["cmd", "/c", "mklink", "/J", str(dst), str(src)], check=True, capture_output=True)
    else:
        dst.symlink_to(os.path.relpath(src, dst.parent), target_is_directory=True)
    return "created"


def main(check: bool) -> int:
    stale = []
    for path, text in render(load_servers()).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path.relative_to(ROOT).as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    for dst, src in LINKS.items():
        print(f"link {dst.relative_to(ROOT).as_posix()} -> {src.relative_to(ROOT).as_posix()}: "
              f"{'missing' if check and not dst.exists() else link(dst, src) if not check else 'ok'}")
    verb = "stale" if check else "written"
    print(f"configs {verb}: {', '.join(stale) or 'none'}")
    return 1 if check and stale else 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv))
